version: '3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=bichobet
  spring-api:
    container_name: spring-api
    build:
      context: ./springboot-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  django-server:
    container_name: django-server
    build:
      context: ./django-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=bichobet
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
  go-scheduler:
    container_name: go-scheduler
    build:
      context: ./go-scheduler
      dockerfile: Dockerfile
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"